steps:
  - id: 'app-source-code'
    name: 'alpine'
    waitFor: ['-']
    volumes:
      - name: 'source-code'
        path: '/build/source-code'
    args: ['cp', '-T', '-r', './', '/build/source-code']

  - id: app-docker-image-build
    name: gcr.io/kaniko-project/executor
    waitFor:
      - 'app-source-code'
    volumes:
      - name: 'source-code'
        path: '/build/source-code'
    args: [
      "--dockerfile=.devops/dockerfiles/Dockerfile",
      "--context=/build/source-code",
      "--destination=gcr.io/$PROJECT_ID/$IMAGE_NAME:$SHORT_SHA",
      "--destination=gcr.io/$PROJECT_ID/$IMAGE_NAME:latest",
      "--cache=true",
      "--cache-ttl=12h"]
